### ISSUE TITLE
Re-render Countdown Component

### ISSUE THREAD

**Issue by edenfoo** [rvehall/countdown-vue#7]
I have a problem which countdown component doesnt re-render when there is a key change detected.

<count-down 
  showDays 
  showHours 
  showMinutes 
  showSeconds 
  :end="countDownEndDuration" 
  :endFunction="endFunction"
  :key="countDownEndDuration" 
></count-down>

Any suggestion?

**Comment by rvehall** [comment]
If you're passing `countDownEndDuration` into `:end`, it shouldn't be changing outside of the component so it wouldn't trigger a key-change.
